<?php

namespace GestionSalleBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{


public function findWeekProf($id) {
	$debut = \date("y").'-'.\date("m").'-'.(\date("d")+7);
	$fin = \date("y").'-'.\date("m").'-'.(\date("d"));
        return $this->createQueryBuilder('p')
            ->where('p.dateDebut < :datedudebut')
            ->setParameter('datedudebut', $debut)
            ->andWhere('p.dateFin > :datedelafin')
            ->setParameter('datedelafin', $fin)
            ->andWhere('p.idUser = :iduser')
            ->setParameter('iduser', $id)
            ->setMaxResults(5)
            ->getQuery()
            ->execute();
	}



public function findWeekStud($id) {
    $debut = \date("y").'-'.\date("m").'-'.(\date("d")+7);
    $fin = \date("y").'-'.\date("m").'-'.(\date("d"));
        return $this->createQueryBuilder('p')
            ->where('p.dateDebut < :datedudebut')
            ->setParameter('datedudebut', $debut)
            ->andWhere('p.dateFin > :datedelafin')
            ->setParameter('datedelafin', $fin)
            ->andWhere('p.idFormation = :idformation')
            ->setParameter('idformation', $id)
            ->setMaxResults(5)
            ->getQuery()
            ->execute();
    }
}
